* hello devcards
  An exploration of turtle programming using
  svg, reagent, core.async and devcards.
** usage
   This requires my complex library which is not yet in clojars.

   [[https://github.com/wbabic/complex]]

   to install the complex library locally:
   #+BEGIN_SRC sh
     git clone git@github.com:wbabic/complex.git
     cd complex
     lein install
   #+END_SRC
   and then:
   #+BEGIN_SRC shell
     lein figwheel

     http://localhost:3449/cards.html
   #+END_SRC

** pixie-turtle
   A restricted svg turtle using simple turtle math
   involving addition and multiplication of whole numbers,
   halving and doubling,
   left and right 90 degree turns
   and is implemented directly in screen coordinates,
   making use of svg transformations.

   [[http://wbabic.github.io/hello-devcards/#!/hello_devcards.pixie_turtle]]
** complex turtle
   A turtle implemented using complex numbers.

   A mapping transforms the turtle into screen coordinates.

   see complex.cljc and mappings.cljc

   used by polygon

** svg bezier
   An exploration of bezier paths, xlink-href use and transform.
   Contains an interactive quadratic bazier with draggable points.

   [[http://wbabic.github.io/hello-devcards/#!/hello_devcards.bezier]]
** polygon
   Turtle commands, command-processor and programs to make
   regular polygons, sections and wheels.

   see polygon.cljc

   Can be used from a clojure repl, from figwheel, or from within a devcard.
** color wheel
   A color wheel made using a complex turtle, polygon and svg.

   [[http://wbabic.github.io/hello-devcards/#!/hello_devcards.color_wheel]]
** colored polygon
   Use polygon and color-wheel
   so that color-wheel manages the current color and
   when polygons are closed,
   the current color is used as the fill color of the polygon.

   [[http://wbabic.github.io/hello-devcards/#!/hello_devcards.colored_polygon]]
** lattice turtle
   A lattice turtle has a position and two heading vectors

   the lattice turtle can

   - move forward and backward along those two dimensions
   - leave a point at each position it visits

   #+BEGIN_SRC clojure
          (reduce
           (fn [state command]
             (process-command command state))
           standard-turtle
           turtle-program)
   #+END_SRC
** projective turtle
   Use the concept of a virtual turtle
   sent forth along the x-axis
   taking one step at a time.

   The original turtle remains fixed
   and with each step, draws a line from i (eye)
   to the virtual turtle
   and in this way, projects a line to a circle.

   The turtle math involves finding the intersection of a line and a circle.
   It is a nice little bit of algebra that makes a direct connection with geometry,
   using turtle graphics to illuminate and animate the process. And in the process,
   Pythagorean triples are generated.

   #+BEGIN_SRC clojure
   [2n/(n^2 - 1), (n^2 + 1)/(n^2 - 1)]
   #+END_SRC
