* hello devcards
  An exploration of turtle programming using svg, reagent and devcards.
** usage
   #+BEGIN_SRC shell
     lein figwheel

     http://localhost:3449/cards.html
   #+END_SRC

   This requires my complex library which is not yet in clojars.

   [[https://github.com/wbabic/complex]]

   to install the complex library locally:
   #+BEGIN_SRC sh
     git clone git@github.com:wbabic/complex.git
     cd complex
     lein install
   #+END_SRC
** pixie-turtle
   A restricted svg turtle using simple turtle math
   involving addition and multiplication of whole numbers,
   halving and doubling,
   left and right 90 degree turns
   and is implemented directly in screen coordinates,
   making use of svg transformations.

** complex turtle
   A turtle implemented using complex numbers.

   A mapping transforms the turtle into screen coordinates.

** polygon
   Turtle commands and program to makes regular polygons.

** color wheel
   A color wheel made using a complex turtle, polygon and svg.

** colored polygon
   Use polygon and color-wheel
   so that color-wheel manages the current color and
   when polygons are closed,
   the current color is used as the fill color of the polygon.

** lattice
   TODO
