* hello devcards
  An exploration of turtle programming using
  svg, reagent, core.async and devcards.
** usage
   #+BEGIN_SRC shell
     lein figwheel

     http://localhost:3449/cards.html
   #+END_SRC

   This requires my complex library which is not yet in clojars.

   [[https://github.com/wbabic/complex]]

   to install the complex library locally:
   #+BEGIN_SRC sh
     git clone git@github.com:wbabic/complex.git
     cd complex
     lein install
   #+END_SRC
** pixie-turtle
   A restricted svg turtle using simple turtle math
   involving addition and multiplication of whole numbers,
   halving and doubling,
   left and right 90 degree turns
   and is implemented directly in screen coordinates,
   making use of svg transformations.

   [[http://wbabic.github.io/hello-devcards/#!/hello_devcards.pixie_turtle]]
** complex turtle
   A turtle implemented using complex numbers.

   A mapping transforms the turtle into screen coordinates.

** svg bezier
   An exploration of bezier paths, xlink-href and use.
   Contains an interactive quadratic bazier with draggable points.
** polygon
   Turtle commands, command-processor and programs to make
   regular polygons, sections and wheels.

   see polygon.cljc

   Can be used from a clojure repl, from figwheel, or from within a devcard.
** color wheel
   A color wheel made using a complex turtle, polygon and svg.
   [[http://wbabic.github.io/hello-devcards/#!/hello_devcards.color_wheel]]
** colored polygon
   Use polygon and color-wheel
   so that color-wheel manages the current color and
   when polygons are closed,
   the current color is used as the fill color of the polygon.

** lattice
   TODO
